apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: msa
spec:
  type: NodePort
  selector:
    app: msa
  ports:
  - protocol: TCP
    port: 80
    nodePort: 31001
    targetPort: 3000
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deploy
  namespace: msa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msa
  template:
    metadata:
      labels:
        app: msa
    spec:
      containers:
      - name: msa
        image: k8s-frontend-main
        imagePullPolicy: Never
        ports:
        - containerPort: 3000