apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-ingress
  namespace: msa
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: backend-signup-service
            port:
              number: 5000
      - path: /data
        pathType: Prefix
        backend:
          service:
            name: backend-data-service
            port:
              number: 5000